services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    networks:
      - korepetycje-net
    environment:
      - NODE_ENV=development
    volumes:
      - ./backend:/app
  
  frontend:
    build: ./frontend
    ports:
      - "3001:3000"
    networks:
      - korepetycje-net
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    command: ["npm", "run", "dev"]
    volumes:
      - ./frontend:/app

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - korepetycje-net
    ports:
      - "5433:5432"

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    command: start-dev
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_USER}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_PASSWORD}
    ports:
      - "8080:8080"
    networks:
      - korepetycje-net

volumes:
  db_data:

networks:
  korepetycje-net:
